# Generated by Django 6.0.3 on 2026-04-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
