# Generated by Django 6.0.3 on 2026-04-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationPage', '0002_userprofile_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
